"""empty message

Revision ID: 779b317bb1fd
Revises: 650af076f9c6
Create Date: 2022-05-26 00:35:58.088079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779b317bb1fd'
down_revision = '650af076f9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_sitecode_key', 'user', type_='unique')
    op.drop_column('user', 'sitecode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sitecode', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_sitecode_key', 'user', ['sitecode'])
    # ### end Alembic commands ###
